# application name
spring.application.name=springboot

# port
server.port = 8080

# datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ngulik-springboot
spring.datasource.username = postgres
spring.datasource.password = irfan123
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa/hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# optional: enable automatic transaction management (when use anotation @Transactional)
spring.transaction.default-timeout=30

# coloring output log
spring.output.ansi.enabled=ALWAYS